config/routes.rb
require "sidekiq/web"
require "sidekiq/cron/web"

Rails.application.routes.draw do
  scope :monitoring do
    if Rails.env.production?
      Sidekiq::Web.use Rack::Auth::Basic do |username, password|
        ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(username), ::Digest::SHA256.hexdigest(ENV["SIDEKIQ_USERNAME"])) &
          ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(password), ::Digest::SHA256.hexdigest(ENV["SIDEKIQ_PASSWORD"]))
      end
    end

    mount Sidekiq::Web, at: "/sidekiq"
  end

  root "pages#home"

  resources :subscriptions, only: [:create]

  resources :last_posts, only: [:index], path: "last"
  get 'feed', to: 'last_posts#feed', format: 'xml', as: :feed

  get "unsubscribe/:token", controller: "unsubscriptions", action: "show", as: "unsubscription"
  get "confirm/:token", controller: "confirm_subscriptions", action: "show", as: "confirm_subscription"
end

app/models/announcement.rb
class Announcement
  def initialize(subject:, body:)
    @subject = subject
    @body = body
  end

  def formatted
    { 'subject': @subject, 'body': @body }.to_json
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hacker_news_post.rb
# == Schema Information
#
# Table name: hacker_news_posts
#
#  id          :bigint           not null, primary key
#  external_id :string
#  url         :string
#  title       :string
#  posted_at   :datetime
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  score       :integer
#
class HackerNewsPost < ApplicationRecord
  validates_presence_of :external_id
  validates_uniqueness_of :external_id

  def self.api_url_for_item_details(item_id)
    "https://hacker-news.firebaseio.com/v0/item/#{item_id}.json"
  end

  def self.api_url_for_show_stories
    "https://hacker-news.firebaseio.com/v0/showstories.json"
  end

  def self.format_post_detail(post_detail)
    external_id = post_detail["id"]
    score = post_detail["score"] || 0
    title = post_detail["title"].sub("Show HN: ", "")
    url = post_detail["url"] || "https://news.ycombinator.com/item?id=#{external_id}"
    posted_at = DateTime.strptime(post_detail["time"].to_s, "%s")

    { url:, score:, title:, posted_at:, external_id: }
  end

  def self.score_ordered_posts_of_last_week
    last_week = last_week_time_period
    starting_at = last_week[:starting_at]
    ending_at = last_week[:ending_at]

    if Rails.env.production?
      cache_expires_at = this_week_time_period[:ending_at]
      posts_ids = Rails.cache.fetch(:score_ordered_posts_of_last_week, expires_at: cache_expires_at) do
        where("posted_at > ?", starting_at).
          where("posted_at <= ?", ending_at).
          order(score: :desc).
          pluck(:id)
      end
      find(posts_ids)
    else
      where("posted_at > ?", starting_at).where("posted_at <= ?", ending_at).order(score: :desc)
    end
  end

  def self.top20_posts_of_last_week
    score_ordered_posts_of_last_week.first(20).to_a
  end

  def self.this_week_time_period
    last_week = last_week_time_period
    {
      starting_at: last_week[:starting_at] + 7.days,
      ending_at: last_week[:ending_at] + 7.days,
    }
  end

  def self.last_week_time_period
    starting_at = Date.tomorrow.prev_occurring(:wednesday).beginning_of_day - 7.days + 12.hours
    {
      starting_at:,
      ending_at: starting_at + 7.days,
    }
  end
end

app/models/subscription.rb
# == Schema Information
#
# Table name: subscriptions
#
#  id            :bigint           not null, primary key
#  email         :string
#  unsub_token   :string
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  confirm_token :string
#  confirmed_at  :datetime
#
class Subscription < ApplicationRecord
  has_secure_token :unsub_token
  has_secure_token :confirm_token

  validates_presence_of :email
  validates_uniqueness_of :email
  validates_format_of :email, with: URI::MailTo::EMAIL_REGEXP

  after_commit :send_welcome_email, on: :create

  def self.confirmed_subscriptions
    where.not(confirmed_at: nil)
  end

  def send_newsletter_email(posts)
    NewsletterMailer.newsletter(id, posts).deliver_later
  end

  def send_welcome_email
    NewsletterMailer.welcome(id).deliver_later
  end

  def send_announcement_email(announcement)
    AnnouncementMailer.announcement(id, announcement).deliver_later
  end

  def confirm!
    update!(confirmed_at: Time.current.utc)
  end

  def confirmed?
    !!confirmed_at
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/confirm_subscriptions_controller.rb
class ConfirmSubscriptionsController < ApplicationController
  before_action :find_subscription, only: [:show]

  def show
    if @subscription.nil?
      redirect_to root_path
      return
    elsif @subscription.confirmed?
      render plain: "Your subscription is already confirmed"
      return
    end

    @subscription.confirm!
    render plain: "Your subscription is now confirmed, see you on wednesday!"
  end

  private

  def find_subscription
    @subscription = Subscription.find_by(confirm_token: params[:token])
  end
end

app/controllers/last_posts_controller.rb
class LastPostsController < ApplicationController
  before_action :find_posts, only: %i[index feed]

  def index; end

  def feed; end

  private

  def find_posts
    @posts = HackerNewsPost.score_ordered_posts_of_last_week
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home; end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  def create
    @subscription = Subscription.new(subscription_params)
    if @subscription.save
      redirect_to root_path, notice: "Please check your inbox(sometimes unfortunately spam) for confirmation mail :^)"
    else
      redirect_to root_path, alert: @subscription.errors.full_messages.first
    end
  end

  private

  def subscription_params
    params.permit(:email)
  end
end

app/controllers/unsubscriptions_controller.rb
class UnsubscriptionsController < ApplicationController
  before_action :find_subscription, only: [:show]

  def show
    if @subscription.nil?
      redirect_to root_path
      return
    end
    @subscription.destroy
    render plain: "Successfully unsubscribed, take care!"
  end

  private

  def find_subscription
    @subscription = Subscription.find_by(unsub_token: params[:token])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/last_posts/index.html.haml
= link_to 'homepage <<', root_path
%h2 showhn.paperboy.digital/last

%h4
  = "#{HackerNewsPost.last_week_time_period[:starting_at].to_s(:short)} -- #{HackerNewsPost.last_week_time_period[:ending_at].to_s(:short)}"

%h3
  = "<top_20>"

- @posts.each_with_index do |p, index|
  - if index == 20
    %h3
      %a{name: "rest"}
        = "</top_20>"
    %hr
  = "#{index + 1}: #{p.title}, score: #{p.score}"
  |
  = link_to 'comments', "https://news.ycombinator.com/item?id=#{p.external_id}", target: :_blank
  %br/
  %br/
  = link_to p.url, p.url, target: :_blank
  %br/
  %br/
  %hr

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShowHN PaperboyDigital</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag asset_path('paperboy_30.png') %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/yegor256/tacit@gh-pages/tacit-css-1.5.5.min.css"/>
    <link rel="alternate" type="application/atom+xml" title="ShowHN Paperboy Digital" href="/feed" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-Q7MZXKTSXE"></script>
    <script>
     window.dataLayer = window.dataLayer || [];
     function gtag(){dataLayer.push(arguments);}
     gtag('js', new Date());

     gtag('config', 'G-Q7MZXKTSXE');
    </script>
  </head>

  <body style="background-color: #F3DFC1">
    <% flash.each do |type, msg| %>
       <div class="alert alert-info page-wrap">
            <%= msg %>
        </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.haml
%body
  .page-wrap
    %h2 newsletter for "show HackerNews"
    %br/
    .box
      = image_tag("paperboy_700.png", size: '300x300', class:"mb-4")
    %br/
    %p delivered weekly on wednesdays

    %form{action: subscriptions_path, method: "POST"}
      %input.form-control{name: "email", placeholder: 'e-mail address', required: true, type: "text"}/
      = hidden_field_tag :authenticity_token, form_authenticity_token

      = submit_tag 'subscribe', class: 'submit_button'

      %br

    %p.mt-5.mb-3.text-muted
      = link_to 'last week\'s projects', last_posts_path
      %br/
      %br/
      = link_to 'source code', 'https://github.com/ccozkan/showhn.paperboy.digital'
      |
      = link_to 'author', 'https://ozkan.cc'
      |
      = link_to 'ccozkan@tutanota.com', 'mailto:ccozkan@tutanota.com'

      %br
      © 2021-2023

app/views/partials/_footer.html.haml
%br/
%br/

This newsletter is b.t.y.b.
= link_to 'showhn.paperboy.digital', root_url
%br/
Feel free to email me at 
= link_to 'hey@paperboy.digital', 'mailto:hey@paperboy.digital'
%br/
= link_to 'unsubscribe', unsubscription_url(token: @subscription.unsub_token), data: {confirm: 'Are you sure you want to unsubscribe?'}